### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by justvanrossum** [BlackFoundryCom/ids-py#2]
- [x] rename `master` branch to `main`
- [x] reconsider IDS object: its methods could just be functions in `ids_py`
- [x] download script: consider folding all datafiles into one so we can load faster
- [ ] set up weekly GH Action to update the data from the upstream (this should be useful: https://github.com/marketplace/actions/create-pull-request)
- [ ] add some basic test cases
- [ ] make repo public
- [ ] upload to PyPI?
